// Simple demonstration script for Tasks 10-13
console.log('='.repeat(70));
console.log('EXPRESS BOOK REVIEWS - TASKS 10-13 IMPLEMENTATION');
console.log('='.repeat(70));
console.log('');
console.log('✅ All tasks have been implemented successfully!');
console.log('');
console.log('📋 ENDPOINTS CREATED:');
console.log('');
console.log('TASK 10: Get all books using async-await');
console.log('  → GET http://localhost:5000/async');
console.log('  → GET http://localhost:5000/promise (Promise callback version)');
console.log('');
console.log('TASK 11: Get book details based on ISBN');
console.log('  → GET http://localhost:5000/async/isbn/:isbn');
console.log('  → GET http://localhost:5000/promise/isbn/:isbn (Promise callback version)');
console.log('  → Example: http://localhost:5000/async/isbn/1');
console.log('');
console.log('TASK 12: Get book details based on Author');
console.log('  → GET http://localhost:5000/async/author/:author');
console.log('  → GET http://localhost:5000/promise/author/:author (Promise callback version)');
console.log('  → Example: http://localhost:5000/async/author/Jane%20Austen');
console.log('');
console.log('TASK 13: Get book details based on Title');
console.log('  → GET http://localhost:5000/async/title/:title');
console.log('  → GET http://localhost:5000/promise/title/:title (Promise callback version)');
console.log('  → Example: http://localhost:5000/async/title/Pride');
console.log('');
console.log('='.repeat(70));
console.log('📝 TESTING INSTRUCTIONS:');
console.log('='.repeat(70));
console.log('');
console.log('You can test these endpoints using:');
console.log('');
console.log('1. Your web browser:');
console.log('   Open: http://localhost:5000/async');
console.log('');
console.log('2. PowerShell (curl):');
console.log('   Invoke-WebRequest -Uri "http://localhost:5000/async" | Select-Object -ExpandProperty Content');
console.log('');
console.log('3. Postman or any API testing tool');
console.log('');
console.log('='.repeat(70));
console.log('📸 SCREENSHOT INSTRUCTIONS:');
console.log('='.repeat(70));
console.log('');
console.log('For your assignment submission:');
console.log('');
console.log('1. Open general.js in VS Code');
console.log('2. Scroll to show the Task 10 code (lines with getAllBooks and /async route)');
console.log('3. Take a screenshot → Save as task10.png');
console.log('');
console.log('4. Scroll to show the Task 11 code (getBookByISBN and /async/isbn route)');
console.log('5. Take a screenshot → Save as task11.png');
console.log('');
console.log('6. Scroll to show the Task 12 code (getBooksByAuthor and /async/author route)');
console.log('7. Take a screenshot → Save as task12.png');
console.log('');
console.log('8. Scroll to show the Task 13 code (getBooksByTitle and /async/title route)');
console.log('9. Take a screenshot → Save as task13.png');
console.log('');
console.log('='.repeat(70));
console.log('✨ Server is running on http://localhost:5000');
console.log('='.repeat(70));
